# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trivy < Formula
  desc "Scanner for vulnerabilities in container images, file systems, and Git repositories, as well as for configuration issues"
  homepage "https://github.com/afdesk/trivy"
  version "0.43.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/afdesk/trivy/releases/download/v0.43.0/trivy_0.43.0_macOS-64bit.tar.gz"
      sha256 "76a725d9678577c396af52fde1f5bfacf08a4d41903e82efb4c7aca41d1ba449"

      def install
        bin.install "trivy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/afdesk/trivy/releases/download/v0.43.0/trivy_0.43.0_macOS-ARM64.tar.gz"
      sha256 "2b503612888075f82736830ee822cc596cd1ce53adcb94d0262982ee8a363c24"

      def install
        bin.install "trivy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/afdesk/trivy/releases/download/v0.43.0/trivy_0.43.0_Linux-ARM64.tar.gz"
      sha256 "876c018bae91121ed36ab5df22b10f0bdafd0cd9c2fee0d850749d47cc0f5384"

      def install
        bin.install "trivy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/afdesk/trivy/releases/download/v0.43.0/trivy_0.43.0_Linux-64bit.tar.gz"
      sha256 "7d16183f086e5eb5d8ff0af73167b9852bfccbe20dbb9c29f0b040e3d5236ce1"

      def install
        bin.install "trivy"
      end
    end
  end

  test do
    system "#{bin}/trivy", "--version"
  end
end
