# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trivy < Formula
  desc "Scanner for vulnerabilities in container images, file systems, and Git repositories, as well as for configuration issues"
  homepage "https://github.com/afdesk/trivy"
  version "0.43.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/afdesk/trivy/releases/download/v0.43.0/trivy_0.43.0_macOS-ARM64.tar.gz"
      sha256 "36e2f404c23f6a777f13c9f2f0669c00ffcce959f4ce33ba68f963f296a84bb0"

      def install
        bin.install "trivy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/afdesk/trivy/releases/download/v0.43.0/trivy_0.43.0_macOS-64bit.tar.gz"
      sha256 "94402114e1049e8353f1145131e2a2c3f1e4aa433394524458e6005f8f1103a0"

      def install
        bin.install "trivy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/afdesk/trivy/releases/download/v0.43.0/trivy_0.43.0_Linux-ARM64.tar.gz"
      sha256 "337818c458fa1744287c0e3fcd71ad74781e2c335ddbda43cb249bc660451065"

      def install
        bin.install "trivy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/afdesk/trivy/releases/download/v0.43.0/trivy_0.43.0_Linux-64bit.tar.gz"
      sha256 "b70288f68a4f6d58b5c8cc6ed4b3a6103aa8d72fcdd1336ad38d8c6ae66af9bc"

      def install
        bin.install "trivy"
      end
    end
  end

  test do
    system "#{bin}/trivy", "--version"
  end
end
